# Generated by Django 2.1.7 on 2019-05-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snippet.Resource')),
                ('local_name', models.CharField(max_length=50)),
                ('sal', models.IntegerField(max_length=20)),
            ],
            bases=('snippet.resource',),
        ),
    ]
