# Generated by Django 2.1.7 on 2019-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_auto_20190602_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('space', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('small', 'car -bike - mini tesla'), ('medium', 'med trucks - water tanker'), ('big', 'trucks')], default='others', max_length=23)),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
