# Generated by Django 2.1.7 on 2019-06-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_vehicle_vehicle_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=44)),
                ('director', models.CharField(max_length=22)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet.Actor')),
            ],
        ),
    ]
