# Generated by Django 2.1.7 on 2019-06-24 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0007_auto_20190625_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippet.Actor'),
        ),
    ]
