# Generated by Django 2.1.7 on 2019-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0008_auto_20190625_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookie',
            fields=[
                ('bookie_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33)),
            ],
        ),
    ]
